modLoader="javafml" #mandatory

loaderVersion="[27,)" #mandatory (24 is current forge version)

credits="Thanks to Harry Talks for his amazing tutorials and Udemy for great Java courses." #optional

authors="kwpugh" #optional

[[mods]] #mandatory
modId="powder_power" #mandatory
version="3.0.13" #mandatory
displayName="Powder Power" #mandatory
description='''
Powder alchemy comes to Minecraft
'''


[[dependencies.powder_power]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.powder_power]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3, 1.14.4]"
    ordering="NONE"
    side="BOTH"
